# Generated by Django 3.1.1 on 2020-09-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.CharField(max_length=100)),
                ('blurb', models.TextField()),
                ('date', models.DateField()),
                ('body_colour', models.CharField(max_length=6)),
                ('text_colour', models.CharField(max_length=6)),
            ],
        ),
    ]
