# Generated by Django 3.1.1 on 2020-09-15 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('layout', models.CharField(choices=[('text', 'Text'), ('text_image', 'Text Image'), ('image', 'Image'), ('video', 'Video'), ('image_2_1_1', 'Image 2 + 1 + 1'), ('image_gallery', 'Image Gallery')], default='text', max_length=32)),
                ('align', models.CharField(choices=[('l', 'Left'), ('r', 'Right')], default='l', max_length=1)),
                ('wide', models.BooleanField(default=False)),
                ('full', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('images', models.ManyToManyField(to='work.WorkSectionImage')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.work')),
            ],
        ),
    ]
