# Generated by Django 3.1.1 on 2020-09-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20200915_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksection',
            name='images',
        ),
    ]
