# Generated by Django 3.1.1 on 2020-09-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20200916_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='work',
            name='hide_header_text',
            field=models.BooleanField(default=False, help_text='Hide the header text if your header image contains the header text'),
        ),
        migrations.AlterField(
            model_name='worksection',
            name='sorting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worksectionimage',
            name='sorting',
            field=models.IntegerField(default=0),
        ),
    ]
