# Generated by Django 3.1.1 on 2020-09-29 20:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20200929_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('-date', 'title')},
        ),
        migrations.AddField(
            model_name='work',
            name='header_text_colour',
            field=colorfield.fields.ColorField(default='#333333', max_length=18),
        ),
    ]
