# Generated by Django 3.1.1 on 2020-10-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20200929_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksection',
            name='align_vertical',
            field=models.CharField(choices=[('t', 'Top'), ('b', 'Bottom'), ('m', 'Middle')], default='t', max_length=1),
        ),
        migrations.AlterField(
            model_name='worksection',
            name='align',
            field=models.CharField(choices=[('l', 'Left'), ('r', 'Right'), ('c', 'Center')], default='l', max_length=1),
        ),
    ]
