# Generated by Django 3.1.1 on 2020-10-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_auto_20201010_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
