# Generated by Django 3.1.1 on 2020-11-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_work_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='link',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
